### ISSUE TITLE
Defaults for f/F/t/T are not consistant with neovim defaults

### ISSUE THREAD

**Issue by cathyprime** [mawkler/demicolon.nvim#2]
tested using this default configuration
```lua
vim.g.mapleader = vim.keycode "<space>"
vim.g.localleader = [[\]]

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end

vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
        'mawkler/demicolon.nvim',
        -- keys = { ';', ',', 't', 'f', 'T', 'F', ']', '[', ']d', '[d' }, -- Uncomment this to lazy load
        dependencies = {
                'nvim-treesitter/nvim-treesitter',
                'nvim-treesitter/nvim-treesitter-textobjects',
        },
        opts = {}
})
```

with default keybinds set by this plugin, pressing 'F' to search backwards works, but repeating with ';' to continue going backwards doesn't work, you have to press ',' to repeat the search backwards, while with default neovim, the behavior of ';' repeats the last command, and pressing ',' does the opposite

example:

`v` - current cursor position
`^` - location after the jump

with this plugin pressing `Fe` works as expected, moving the cursor to the previous e
```
           v
memememememe
         ^
```
while pressing ';' after it would move to the previous position
```
         v
memememememe
           ^
```
but this is vanilla neovim behavior, it should continue moving the same way
```
         v
memememememe
       ^
```

**Comment by cathyprime** [comment]
I have tracked down the issue to those lines: https://github.com/mawkler/demicolon.nvim/blob/21721dfbeb56166863937e44548c7bc036751d3d/lua/demicolon/keymaps.lua#L10-L11, instead they should have:
```lua
  vim.keymap.set(nxo, ';', ts_repeatable_move.repeat_last_move)
  vim.keymap.set(nxo, ',', ts_repeatable_move.repeat_last_move_opposite)
```
to work like vanilla neovim

**Comment by mawkler** [comment]
@Cathyprime Yes, I'm aware that this is inconsistent with Neovim's default. However, in my opinion the default behaviour makes less sense because to know which direction `;`/`,` will move you need to remember in which direction you did the original `t`/`T`/`f`/`F` jump. I think a lot of people prefer the "stateless" behaviour (i.e. `;` jumps to the right, `,` jumps to the left) because the helpdocs even explicitly advise you how to fix this in `:help getcharsearch()`. Also `repeat_last_move_next`/`repeat_last_move_previous` aren't implemented by me, but by nvim-treesitter-textobjects.

If you want the default behaviour you can simply disable demicolon's default repeat keymaps option and set your own custom ones like so:

```lua
{
  'mawkler/demicolon.nvim',
  dependencies = {
    'nvim-treesitter/nvim-treesitter',
    'nvim-treesitter/nvim-treesitter-textobjects',
  },
  config = function()
    require('demicolon').setup({
      keymaps = {
        repeat_motions = false,
      },
    })

    local ts_repeatable_move = require('nvim-treesitter.textobjects.repeatable_move')
    local nxo = { 'n', 'x', 'o' }

    vim.keymap.set(nxo, ';', ts_repeatable_move.repeat_last_move)
    vim.keymap.set(nxo, ',', ts_repeatable_move.repeat_last_move_opposite)
  end
}
```

If this were a more intrusive change to some default behaviour I would have agreed that it's better to respect the default way, but since it is very easy to change the behaviour back to default I personally think that it's fine for demicolon lean into (in my opinion) intuitive over default behaviour.

I can add this info to the README though if anyone else wonders how to configure it to use the default behaviour.

**Comment by cathyprime** [comment]
thank you for the quick response. I've managed to fix it myself already, I was just confused as to why this is inconsistent with the defaults. I think adding this information to the docs is the best way to go about it, thank you :)
